import { IUser } from './user';
import { IGroup } from './groups';

export type IAccount = IUser | IGroup;

export * from './app';
export * from './article';
export * from './attachment';
export * from './audio';
export * from './audio-message';
export * from './base';
export * from './board';
export * from './chat';
export * from './comment';
export * from './common';
export * from './conversation';
export * from './dialog';
export * from './doc';
export * from './event';
export * from './friends';
export * from './geo';
export * from './gift';
export * from './groups';
export * from './keyboard';
export * from './like';
export * from './link';
export * from './media';
export * from './message';
export * from './note';
export * from './notifications';
export * from './page';
export * from './photo';
export * from './poll';
export * from './repost';
export * from './sticker';
export * from './user';
export * from './video';
export * from './wall';
